# Factors Finder
10 PRINT "FIND ALL FACTORS"
20 PRINT "ENTER A NUMBER: ";
30 INPUT N
40 PRINT "FACTORS OF "; N; ":"
50 FOR I = 1 TO N
60   IF N - I * INT(N / I) = 0 THEN PRINT I; " ";
70 NEXT I
80 PRINT
90 PRINT "DONE."
